import type { ModuleConfig, ModuleId } from './types'

export const MODULE_REGISTRY: Record<ModuleId, ModuleConfig> = {
  hr: {
    id: 'hr',
    name: 'HR и команда',
    description: 'Управление вакансиями, кандидатами и процессом найма',
    icon: 'Users',
    basePath: '/hr',
    menuItems: [
      // Найм
      { label: 'Дашборд',          href: '/hr/dashboard',         icon: 'LayoutDashboard' },
      { label: 'Вакансии',         href: '/hr/vacancies',         icon: 'Briefcase' },
      { label: 'Кандидаты',        href: '/hr/candidates',        icon: 'UserCheck' },
      { label: 'Talent Pool',      href: '/hr/talent-pool',       icon: 'Users' },
      { label: 'Аналитика найма',  href: '/hr/analytics',         icon: 'BarChart3' },
      { label: 'Календарь',        href: '/hr/calendar',          icon: 'Calendar' },
      { label: 'Настройки найма',  href: '/hr/hiring-settings',   icon: 'Settings' },
      // Адаптация
      { label: 'Онбординг',              href: '/hr/onboarding',              icon: 'GraduationCap' },
      { label: 'Назначения',             href: '/hr/assignments',             icon: 'ClipboardList' },
      { label: 'Аналитика адаптации',    href: '/hr/adaptation-analytics',    icon: 'TrendingUp' },
      // Персонал
      { label: 'Сотрудники',             href: '/hr/employees',               icon: 'Users' },
      { label: 'Обучение',               href: '/hr/courses',                 icon: 'BookOpen' },
      { label: 'Развитие',               href: '/hr/development',             icon: 'Target' },
      { label: 'Удержание',              href: '/hr/retention',               icon: 'Shield' },
      { label: 'Аналитика персонала',    href: '/hr/people-analytics',        icon: 'PieChart' },
      // CRM
      { label: 'Компании',              href: '/sales/clients',              icon: 'Building2' },
      { label: 'Контакты',              href: '/sales/contacts',             icon: 'Users' },
      // Legacy (not in menu groups, but pages still exist)
      { label: 'Обзор',          href: '/hr/overview',    icon: 'LayoutDashboard' },
      { label: 'Overview2',      href: '/hr/overview2',   icon: 'LayoutDashboard' },
      { label: 'Воронка',        href: '/hr/funnel',      icon: 'TrendingDown' },
      { label: 'Демо-редактор',  href: '/hr/demo-editor', icon: 'Layers' },
      { label: 'Уведомления',       href: '/hr/settings/notifications',  icon: 'Bell' },
      { label: 'Расписание',        href: '/hr/settings/schedule',       icon: 'Clock' },
      { label: 'Этапы воронки',     href: '/hr/settings/funnel-stages',  icon: 'GitBranch' },
      { label: 'Шаблоны сообщений', href: '/hr/settings/templates',      icon: 'FileText' },
      { label: 'Источники',         href: '/hr/settings/sources',        icon: 'Globe' },
      { label: 'Планы',         href: '/hr/adaptation/plans',      icon: 'ClipboardList' },
      { label: 'Назначения (v1)', href: '/hr/adaptation/assignments', icon: 'UserCheck2' },
      { label: 'Геймификация',  href: '/hr/adaptation/gamification', icon: 'Trophy' },
      { label: 'Аналитика (v1)', href: '/hr/adaptation/analytics',   icon: 'BarChart2' },
      { label: 'Наставничество', href: '/hr/buddy',                   icon: 'HeartHandshake' },
      { label: 'Пребординг',  href: '/hr/preboarding',               icon: 'Rocket' },
      { label: 'Offboarding', href: '/hr/offboarding',                icon: 'UserMinus' },
      { label: 'Сертификаты',  href: '/hr/certificates',            icon: 'Award' },
      { label: 'Навыки',       href: '/hr/skills',                  icon: 'Zap' },
      { label: 'Оценки',       href: '/hr/assessments',             icon: 'ClipboardCheck' },
      { label: 'Flight Risk',      href: '/hr/flight-risk',             icon: 'AlertTriangle' },
      { label: 'Пульс-опросы',     href: '/hr/pulse-surveys',           icon: 'MessageSquare' },
      { label: 'Reskilling',       href: '/hr/reskilling',              icon: 'Brain' },
      { label: 'Predictive Hiring',href: '/hr/predictive-hiring',       icon: 'Radar' },
      { label: 'Маркетплейс',  href: '/hr/marketplace',             icon: 'Store' },
      { label: 'AI-ассистент', href: '/hr/ai-assistant',             icon: 'Bot' },
      { label: 'Обзор',         href: '/overview',       icon: 'LayoutDashboard' },
      { label: 'Рефералы',      href: '/referrals',      icon: 'Share2' },
    ],
  },
  knowledge: {
    id: 'knowledge',
    name: 'База знаний',
    description: 'Корпоративная база знаний',
    icon: 'BookMarked',
    basePath: '/knowledge',
    menuItems: [
      { label: 'База знаний', href: '/knowledge', icon: 'BookMarked' },
    ],
  },
  marketing: {
    id: 'marketing',
    name: 'Маркетинг и продвижение',
    description: 'Контент, SEO, реклама и маркетинговая аналитика',
    icon: 'Megaphone',
    basePath: '/marketing',
    menuItems: [
      { label: 'Дашборд',         href: '/marketing/dashboard',   icon: 'LayoutDashboard' },
      { label: 'Контент',         href: '/marketing/content',     icon: 'FileText' },
      { label: 'SEO',             href: '/marketing/seo',         icon: 'Search' },
      { label: 'Рекламные кампании', href: '/marketing/campaigns', icon: 'Megaphone' },
      { label: 'Соцсети',         href: '/marketing/social',      icon: 'Globe' },
      { label: 'Email-рассылки',  href: '/marketing/email',       icon: 'MessageSquare' },
      { label: 'Лендинги',        href: '/marketing/landings',    icon: 'Layers' },
      { label: 'Отзывы',          href: '/marketing/reviews',     icon: 'MessageSquare' },
      { label: 'Аналитика',       href: '/marketing/analytics',   icon: 'TrendingUp' },
      { label: 'Бюджет',          href: '/marketing/budget',      icon: 'CreditCard' },
    ],
  },
  sales: {
    id: 'sales',
    name: 'Продажи и развитие',
    description: 'CRM, воронка продаж, клиенты и аналитика',
    icon: 'DollarSign',
    basePath: '/sales',
    menuItems: [
      { label: 'Дашборд',         href: '/sales/dashboard',   icon: 'LayoutDashboard' },
      { label: 'Сделки',          href: '/sales/deals',       icon: 'Briefcase' },
      { label: 'Воронка',         href: '/sales/pipeline',    icon: 'TrendingDown' },
      { label: 'Компании',         href: '/sales/clients',     icon: 'Building2' },
      { label: 'Контакты',        href: '/sales/contacts',    icon: 'Users' },
      { label: 'Задачи',          href: '/sales/tasks',       icon: 'ClipboardList' },
      { label: 'Встречи',         href: '/sales/meetings',    icon: 'Calendar' },
      { label: 'Продукты',        href: '/sales/products',    icon: 'Layers' },
      { label: 'Аналитика',       href: '/sales/analytics',   icon: 'BarChart3' },
      { label: 'Прогнозы',        href: '/sales/forecasts',   icon: 'TrendingUp' },
    ],
  },
  b2b: {
    id: 'b2b',
    name: 'Торговля B2B',
    description: 'Оптовые продажи, дилерская сеть и договоры',
    icon: 'Handshake',
    basePath: '/b2b',
    menuItems: [],
  },
  ecommerce: {
    id: 'ecommerce',
    name: 'E-commerce',
    description: 'Интернет-магазин, заказы и интеграции с маркетплейсами',
    icon: 'Store',
    basePath: '/ecommerce',
    menuItems: [],
  },
  logistics: {
    id: 'logistics',
    name: 'Логистика и склад',
    description: 'Управление доставкой и складом',
    icon: 'Truck',
    basePath: '/logistics',
    menuItems: [
      { label: 'Дашборд',      href: '/logistics/dashboard',  icon: 'LayoutDashboard' },
      { label: 'Товары',       href: '/logistics/inventory',  icon: 'Package' },
      { label: 'Склады',       href: '/logistics/warehouses', icon: 'Warehouse' },
      { label: 'Заказы',       href: '/logistics/orders',     icon: 'ShoppingCart' },
      { label: 'Отгрузки',     href: '/logistics/shipments',  icon: 'Truck' },
      { label: 'Возвраты',     href: '/logistics/returns',    icon: 'RotateCcw' },
      { label: 'Поставщики',   href: '/logistics/suppliers',  icon: 'Users' },
      { label: 'Закупки',      href: '/logistics/purchases',  icon: 'ClipboardList' },
      { label: 'Аналитика',    href: '/logistics/analytics',  icon: 'BarChart3' },
      { label: 'Отчёты',       href: '/logistics/reports',    icon: 'FileText' },
    ],
  },
}
