import type { ModuleConfig, ModuleId } from './types'

export const MODULE_REGISTRY: Record<ModuleId, ModuleConfig> = {
  hr: {
    id: 'hr',
    name: 'HR и найм',
    description: 'Управление вакансиями, кандидатами и процессом найма',
    icon: 'Users',
    basePath: '/hr',
    menuItems: [
      { label: 'Вакансии',      href: '/hr/vacancies',   icon: 'Briefcase' },
      { label: 'Кандидаты',     href: '/hr/candidates',  icon: 'UserCheck' },
      { label: 'Демо-редактор', href: '/hr/demo-editor', icon: 'Layers' },
      { label: 'Интервью',      href: '/hr/interviews',  icon: 'Calendar' },
      { label: 'Talent Pool',   href: '/hr/talent-pool', icon: 'Database' },
      { label: 'Онбординг',     href: '/hr/onboarding',            icon: 'Rocket' },
      { label: 'Планы',         href: '/hr/adaptation/plans',      icon: 'ClipboardList' },
      { label: 'Назначения',    href: '/hr/adaptation/assignments', icon: 'UserCheck2' },
      { label: 'Геймификация',  href: '/hr/adaptation/gamification', icon: 'Trophy' },
      { label: 'Аналитика',    href: '/hr/adaptation/analytics',    icon: 'BarChart2' },
      { label: 'Наставничество', href: '/hr/buddy',                   icon: 'HeartHandshake' },
      { label: 'Курсы',        href: '/hr/courses',                 icon: 'BookOpen' },
      { label: 'Сертификаты',  href: '/hr/certificates',            icon: 'Award' },
      { label: 'Навыки',       href: '/hr/skills',                  icon: 'Zap' },
      { label: 'Оценки',       href: '/hr/assessments',             icon: 'ClipboardCheck' },
      { label: 'Flight Risk',  href: '/hr/flight-risk',             icon: 'AlertTriangle' },
      { label: 'Пульс-опросы', href: '/hr/pulse-surveys',           icon: 'MessageSquare' },
      { label: 'Аналитика',     href: '/hr/analytics',   icon: 'BarChart3' },
      { label: 'Обзор',         href: '/overview',       icon: 'LayoutDashboard' },
      { label: 'Рефералы',      href: '/referrals',      icon: 'Share2' },
    ],
  },
  marketing: {
    id: 'marketing',
    name: 'Маркетинг',
    description: 'Контент, SEO и маркетинговая аналитика',
    icon: 'Megaphone',
    basePath: '/marketing',
    menuItems: [
      { label: 'Контент',   href: '/marketing/content',  icon: 'FileText' },
      { label: 'SEO',       href: '/marketing/seo',      icon: 'Search' },
      { label: 'Аналитика', href: '/marketing/analytics',icon: 'TrendingUp' },
    ],
  },
  sales: {
    id: 'sales',
    name: 'Продажи',
    description: 'Управление продажами и клиентской базой',
    icon: 'DollarSign',
    basePath: '/sales',
    menuItems: [],
  },
  logistics: {
    id: 'logistics',
    name: 'Логистика',
    description: 'Управление доставкой и складом',
    icon: 'Truck',
    basePath: '/logistics',
    menuItems: [],
  },
}
