import type { ModuleConfig, ModuleId } from './types'

export const MODULE_REGISTRY: Record<ModuleId, ModuleConfig> = {
  hr: {
    id: 'hr',
    name: 'HR и команда',
    description: 'Управление вакансиями, кандидатами и процессом найма',
    icon: 'Users',
    basePath: '/hr',
    menuItems: [
      // Найм
      { label: 'Дашборд',          href: '/hr/dashboard',         icon: 'LayoutDashboard' },
      { label: 'Вакансии',         href: '/hr/vacancies',         icon: 'Briefcase' },
      { label: 'Библиотека',       href: '/hr/library',           icon: 'Library' },
      { label: 'Кандидаты',        href: '/hr/candidates',        icon: 'UserCheck' },
      { label: 'Talent Pool',      href: '/hr/talent-pool',       icon: 'Users' },
      { label: 'Аналитика найма',  href: '/hr/analytics',         icon: 'BarChart3' },
      { label: 'Календарь',        href: '/hr/calendar',          icon: 'Calendar' },
      { label: 'Настройки найма',  href: '/hr/hiring-settings',   icon: 'Settings' },
      { label: 'Интеграции',       href: '/hr/integrations',      icon: 'Plug' },
      // Адаптация
      { label: 'Ввод информации',         href: '/hr/onboarding',              icon: 'GraduationCap' },
      { label: 'Назначения',             href: '/hr/assignments',             icon: 'ClipboardList' },
      { label: 'Аналитика адаптации',    href: '/hr/adaptation-analytics',    icon: 'TrendingUp' },
      // Персонал
      { label: 'Сотрудники',             href: '/hr/employees',               icon: 'Users' },
      { label: 'Обучение',               href: '/hr/courses',                 icon: 'BookOpen' },
      { label: 'Развитие',               href: '/hr/development',             icon: 'Target' },
      { label: 'Удержание',              href: '/hr/retention',               icon: 'Shield' },
      { label: 'Аналитика персонала',    href: '/hr/people-analytics',        icon: 'PieChart' },
      // Legacy (not in menu groups, but pages still exist)
      { label: 'Обзор',          href: '/hr/overview',    icon: 'LayoutDashboard' },
      { label: 'Overview2',      href: '/hr/overview2',   icon: 'LayoutDashboard' },
      { label: 'Воронка',        href: '/hr/funnel',      icon: 'TrendingDown' },
      { label: 'Демо-редактор',  href: '/hr/demo-editor', icon: 'Layers' },
      { label: 'Уведомления',       href: '/hr/settings/notifications',  icon: 'Bell' },
      { label: 'Расписание',        href: '/hr/settings/schedule',       icon: 'Clock' },
      { label: 'Этапы воронки',     href: '/hr/settings/funnel-stages',  icon: 'GitBranch' },
      { label: 'Шаблоны сообщений', href: '/hr/settings/templates',      icon: 'FileText' },
      { label: 'Источники',         href: '/hr/settings/sources',        icon: 'Globe' },
      { label: 'Планы',         href: '/hr/adaptation/plans',      icon: 'ClipboardList' },
      { label: 'Назначения (v1)', href: '/hr/adaptation/assignments', icon: 'UserCheck2' },
      { label: 'Геймификация',  href: '/hr/adaptation/gamification', icon: 'Trophy' },
      { label: 'Аналитика (v1)', href: '/hr/adaptation/analytics',   icon: 'BarChart2' },
      { label: 'Наставничество', href: '/hr/buddy',                   icon: 'HeartHandshake' },
      { label: 'Пребординг',  href: '/hr/preboarding',               icon: 'Rocket' },
      { label: 'Offboarding', href: '/hr/offboarding',                icon: 'UserMinus' },
      { label: 'Сертификаты',  href: '/hr/certificates',            icon: 'Award' },
      { label: 'Навыки',       href: '/hr/skills',                  icon: 'Zap' },
      { label: 'Оценки',       href: '/hr/assessments',             icon: 'ClipboardCheck' },
      { label: 'Flight Risk',      href: '/hr/flight-risk',             icon: 'AlertTriangle' },
      { label: 'Пульс-опросы',     href: '/hr/pulse-surveys',           icon: 'MessageSquare' },
      { label: 'Reskilling',       href: '/hr/reskilling',              icon: 'Brain' },
      { label: 'Predictive Hiring',href: '/hr/predictive-hiring',       icon: 'Radar' },
      { label: 'Маркетплейс',  href: '/hr/marketplace',             icon: 'Store' },
      { label: 'AI-ассистент', href: '/hr/ai-assistant',             icon: 'Bot' },
      { label: 'Обзор',         href: '/overview',       icon: 'LayoutDashboard' },
      { label: 'Рефералы',      href: '/referrals',      icon: 'Share2' },
    ],
  },
  learning: {
    id: 'learning',
    name: 'Обучение',
    description: 'Курсы, тренировки, планы и рейтинг обучения',
    icon: 'GraduationCap',
    basePath: '/learning',
    menuItems: [
      { label: 'Дашборд',        href: '/learning/dashboard',    icon: 'LayoutDashboard' },
      { label: 'AI-курсы',       href: '/learning/courses',      icon: 'Sparkles' },
      { label: 'Тренировки',     href: '/learning/training',     icon: 'Target' },
      { label: 'Планы обучения', href: '/learning/plans',        icon: 'GraduationCap' },
      { label: 'Рейтинг',        href: '/learning/achievements', icon: 'Trophy' },
    ],
  },
  knowledge: {
    id: 'knowledge',
    name: 'База знаний',
    description: 'Корпоративная база знаний',
    icon: 'BookMarked',
    basePath: '/knowledge-v2',
    menuItems: [
      { label: 'Дашборд БЗ',     href: '/knowledge-v2/dashboard',     icon: 'LayoutDashboard' },
      { label: 'Все материалы',  href: '/knowledge-v2',               icon: 'BookOpen' },
      { label: 'Создать',        href: '/knowledge-v2/create',        icon: 'Plus' },
      { label: 'На проверке',    href: '/knowledge-v2/review',        icon: 'ClipboardCheck' },
      { label: 'AI-токены',      href: '/knowledge-v2/tokens',        icon: 'Coins' },
      { label: 'Настройки БЗ',   href: '/knowledge-v2/settings',      icon: 'Settings' },
    ],
  },
  sales: {
    id: 'sales',
    name: 'CRM',
    description: 'Управление компаниями и контактами',
    icon: 'Briefcase',
    basePath: '/sales',
    menuItems: [
      { label: 'Сделки',    href: '/sales/deals',      icon: 'Handshake' },
      { label: 'Компании',  href: '/sales/clients',    icon: 'Building2' },
      { label: 'Контакты',  href: '/sales/contacts',   icon: 'Users' },
      { label: 'Заявки',    href: '/sales/requests',   icon: 'Inbox' },
      { label: 'Журнал',    href: '/sales/visit-log',  icon: 'Activity' },
    ],
  },
  tasks: {
    id: 'tasks',
    name: 'Задачи и проекты',
    description: 'Управление задачами, проектами и аналитика эффективности',
    icon: 'CheckSquare',
    basePath: '/tasks',
    menuItems: [
      { label: 'Доска',      href: '/tasks',            icon: 'LayoutGrid' },
      { label: 'Проекты',    href: '/tasks/projects',   icon: 'FolderKanban' },
      { label: 'Аналитика',  href: '/tasks/analytics',  icon: 'BarChart3' },
    ],
  },
  marketing: {
    id: 'marketing',
    name: 'Маркетинг',
    description: 'Контент, SEO, реклама и маркетинговая аналитика',
    icon: 'Megaphone',
    basePath: '/marketing',
    menuItems: [
      { label: 'Дашборд',         href: '/marketing/dashboard',   icon: 'LayoutDashboard' },
      { label: 'Контент',         href: '/marketing/content',     icon: 'FileText' },
      { label: 'SEO',             href: '/marketing/seo',         icon: 'Search' },
      { label: 'Рекламные кампании', href: '/marketing/campaigns', icon: 'Megaphone' },
      { label: 'Соцсети',         href: '/marketing/social',      icon: 'Globe' },
      { label: 'Email-рассылки',  href: '/marketing/email',       icon: 'MessageSquare' },
      { label: 'Лендинги',        href: '/marketing/landings',    icon: 'Layers' },
      { label: 'Отзывы',          href: '/marketing/reviews',     icon: 'MessageSquare' },
      { label: 'Аналитика',       href: '/marketing/analytics',   icon: 'TrendingUp' },
      { label: 'Бюджет',          href: '/marketing/budget',      icon: 'CreditCard' },
      { label: 'Настройки',       href: '/marketing/settings',    icon: 'Settings' },
    ],
  },
  b2b: {
    id: 'b2b',
    name: 'Торговля B2B',
    description: 'Оптовые продажи, дилерская сеть и договоры',
    icon: 'Briefcase',
    basePath: '/b2b',
    menuItems: [
      { label: 'Дашборд',    href: '/b2b',             icon: 'LayoutDashboard' },
      { label: 'Аккаунты',   href: '/b2b/accounts',    icon: 'Building2' },
      { label: 'Тендеры',    href: '/b2b/tenders',     icon: 'ClipboardList' },
      { label: 'Аналитика',  href: '/b2b/analytics',   icon: 'BarChart3' },
      { label: 'Настройки',  href: '/b2b/settings',    icon: 'Settings' },
    ],
  },
  ecommerce: {
    id: 'ecommerce',
    name: 'E-commerce',
    description: 'Интернет-магазин, заказы и интеграции с маркетплейсами',
    icon: 'Store',
    basePath: '/ecommerce',
    menuItems: [],
  },
  booking: {
    id: 'booking',
    name: 'Бронирование',
    description: 'Запись клиентов на услуги и управление расписанием',
    icon: 'CalendarCheck',
    basePath: '/booking',
    menuItems: [
      { label: 'Календарь',  href: '/booking',           icon: 'Calendar' },
      { label: 'Услуги',     href: '/booking/services',  icon: 'ListChecks' },
      { label: 'Ресурсы',    href: '/booking/resources', icon: 'Users' },
      { label: 'Настройки',  href: '/booking/settings',  icon: 'Settings' },
    ],
  },
  warehouse: {
    id: 'warehouse',
    name: 'Склад',
    description: 'Товары, склады, заказы, отгрузки',
    icon: 'Warehouse',
    basePath: '/warehouse',
    menuItems: [
      { label: 'Дашборд',      href: '/warehouse/dashboard',  icon: 'LayoutDashboard' },
      { label: 'Товары',       href: '/warehouse/inventory',  icon: 'Package' },
      { label: 'Склады',       href: '/warehouse/warehouses', icon: 'Warehouse' },
      { label: 'Заказы',       href: '/warehouse/orders',     icon: 'ShoppingCart' },
      { label: 'Отгрузки',     href: '/warehouse/shipments',  icon: 'Truck' },
      { label: 'Возвраты',     href: '/warehouse/returns',    icon: 'RotateCcw' },
      { label: 'Поставщики',   href: '/warehouse/suppliers',  icon: 'Users' },
      { label: 'Закупки',      href: '/warehouse/purchases',  icon: 'ClipboardList' },
      { label: 'Аналитика',    href: '/warehouse/analytics',  icon: 'BarChart3' },
      { label: 'Отчёты',       href: '/warehouse/reports',    icon: 'FileText' },
    ],
  },
  logistics: {
    id: 'logistics',
    name: 'Логистика',
    description: 'Грузоперевозки, трекинг, перевозчики, расчёты ставок',
    icon: 'Truck',
    basePath: '/logistics',
    menuItems: [
      { label: 'Дашборд',     href: '/logistics/dashboard',  icon: 'LayoutDashboard' },
      { label: 'Запросы',     href: '/logistics/requests',   icon: 'Inbox' },
      { label: 'Расчёты',     href: '/logistics/quotes',     icon: 'Calculator' },
      { label: 'Перевозки',   href: '/logistics/shipments',  icon: 'Ship' },
      { label: 'Перевозчики', href: '/logistics/carriers',   icon: 'Building2' },
      { label: 'Настройки',   href: '/logistics/settings',   icon: 'Settings' },
    ],
  },
  dialer: {
    id: 'dialer',
    name: 'Бот-звонарь',
    description: 'AI-агент для исходящих звонков по скриптам',
    icon: 'PhoneOutgoing',
    basePath: '/dialer',
    menuItems: [
      { label: 'Дашборд',    href: '/dialer',           icon: 'LayoutDashboard' },
      { label: 'Скрипты',    href: '/dialer/scripts',   icon: 'FileText' },
      { label: 'История',    href: '/dialer/history',   icon: 'ClipboardList' },
      { label: 'Настройки',  href: '/dialer/settings',  icon: 'Settings' },
    ],
  },
  qc: {
    id: 'qc',
    name: 'ОКК',
    description: 'AI-анализ записей звонков менеджеров',
    icon: 'Headphones',
    basePath: '/qc',
    menuItems: [
      { label: 'Дашборд',    href: '/qc',             icon: 'LayoutDashboard' },
      { label: 'Чек-листы',  href: '/qc/checklists',  icon: 'ClipboardCheck' },
      { label: 'Настройки',  href: '/qc/settings',    icon: 'Settings' },
    ],
  },
}
