export interface CronEntry {
  name: string
  endpoint: string
  schedule: string | null
  description: string
}

export const CRON_REGISTRY: CronEntry[] = [
  {
    name: "adaptation",
    endpoint: "/api/cron/adaptation",
    schedule: null,
    description: "Продвигает шаги адаптационных назначений и отправляет задания",
  },
  {
    name: "ai-chatbot-watcher",
    endpoint: "/api/cron/ai-chatbot-watcher",
    schedule: "0 * * * *",
    description: "AI-наблюдатель: аудит переписки чат-бота на аномалии",
  },
  {
    name: "ai-rop-billing",
    endpoint: "/api/cron/ai-rop-billing",
    schedule: "0 1 * * *",
    description: "AI-РОП: ежесуточный биллинг и проверка лимитов",
  },
  {
    name: "ai-rop-crm-outcomes",
    endpoint: "/api/cron/ai-rop-crm-outcomes",
    schedule: "0 */6 * * *",
    description: "AI-РОП: синхронизация исходов сделок из CRM",
  },
  {
    name: "ai-rop-import",
    endpoint: "/api/cron/ai-rop-import",
    schedule: "*/5 * * * *",
    description: "AI-РОП: импорт email и чатов из подключённых каналов",
  },
  {
    name: "ai-rop-process",
    endpoint: "/api/cron/ai-rop-process",
    schedule: "* * * * *",
    description: "AI-РОП: обработка очереди звонков и сообщений",
  },
  {
    name: "ai-rop-reports",
    endpoint: "/api/cron/ai-rop-reports",
    schedule: "* * * * *",
    description: "AI-РОП: автоотправка отчётов по расписанию из rop_report_schedules",
  },
  {
    name: "ai-rop-retry",
    endpoint: "/api/cron/ai-rop-retry",
    schedule: "*/30 * * * *",
    description: "AI-РОП: повтор неудачных задач транскрипции и скоринга",
  },
  {
    name: "auto-invoices",
    endpoint: "/api/cron/auto-invoices",
    schedule: "0 6 * * *",
    description: "Автовыставление счетов за 7 дней до конца оплаченного периода",
  },
  {
    name: "avito-incoming-messages",
    endpoint: "/api/cron/avito-incoming-messages",
    schedule: "*/15 * * * *",
    description: "Резервный опрос Авито-сообщений (страховка на случай сбоев webhook)",
  },
  {
    name: "b9-status-sanity",
    endpoint: "/api/cron/b9-status-sanity",
    schedule: "0 * * * *",
    description: "Sanity-check B9: поиск расхождений stage vs funnelV2StateJson (read-only)",
  },
  {
    name: "check-subscriptions",
    endpoint: "/api/cron/check-subscriptions",
    schedule: null,
    description: "Переводит компании с истёкшим триалом в статус expired",
  },
  {
    name: "data-retention",
    endpoint: "/api/cron/data-retention",
    schedule: "0 1 * * *",
    description: "Удаление данных по политике хранения (GDPR/ФЗ-152)",
  },
  {
    name: "dev-activity",
    endpoint: "/api/cron/dev-activity",
    schedule: "*/15 * * * *",
    description: "Трекинг активности разработки для внутренней статистики",
  },
  {
    name: "flight-price-watch",
    endpoint: "/api/cron/flight-price-watch",
    schedule: "0 4,10,16,22 * * *",
    description: "Мониторинг цен на авиабилеты для командировочного модуля",
  },
  {
    name: "flight-risk-alerts",
    endpoint: "/api/cron/flight-risk-alerts",
    schedule: null,
    description: "Уведомления о переходе сотрудников в высокую/критическую зону риска увольнения",
  },
  {
    name: "follow-up",
    endpoint: "/api/cron/follow-up",
    schedule: null,
    description: "Дожим кандидатов: отправка сообщений по активным кампаниям",
  },
  {
    name: "funnel-v2-tick",
    endpoint: "/api/cron/funnel-v2-tick",
    schedule: "*/5 * * * *",
    description: "Тик рантайма воронки v2: запуск отложенных действий по candidates",
  },
  {
    name: "ghost-candidate-cleanup",
    endpoint: "/api/cron/ghost-candidate-cleanup",
    schedule: "30 0 * * *",
    description: "Удаление кандидатов-призраков (брошенные анонимные визиты)",
  },
  {
    name: "health-check",
    endpoint: "/api/cron/health-check",
    schedule: null,
    description: "Проверка регулярности прогонов критичных кронов, alert при просрочке",
  },
  {
    name: "hh-cleanup-stuck",
    endpoint: "/api/cron/hh-cleanup-stuck",
    schedule: null,
    description: "Перевод зависших hh_responses в статус orphaned (вызывается из hh-import)",
  },
  {
    name: "hh-import",
    endpoint: "/api/cron/hh-import",
    schedule: "* * * * *",
    description: "Импорт откликов с hh.ru и разбор очереди AI-обработки",
  },
  {
    name: "hh-import-burst",
    endpoint: "/api/cron/hh-import-burst",
    schedule: null,
    description: "Пакетный запуск N итераций hh-import (UI-кнопка «Разобрать всё»)",
  },
  {
    name: "hh-incoming-messages",
    endpoint: "/api/cron/hh-incoming-messages",
    schedule: "*/15 * * * *",
    description: "Обработка входящих сообщений от кандидатов в hh-чатах",
  },
  {
    name: "hh-negotiation-sync",
    endpoint: "/api/cron/hh-negotiation-sync",
    schedule: "*/15 * * * *",
    description: "Синхронизация стадий откликов с hh в платформу",
  },
  {
    name: "hh-token-refresh",
    endpoint: "/api/cron/hh-token-refresh",
    schedule: "0 5 * * *",
    description: "Обновление истёкших hh OAuth-токенов у дормантных компаний",
  },
  {
    name: "hh-vacancy-sync",
    endpoint: "/api/cron/hh-vacancy-sync",
    schedule: "30 2 * * *",
    description: "Синхронизация статуса публикации вакансий с hh (hh_archived, hh_expires_at)",
  },
  {
    name: "hiring-watchdog",
    endpoint: "/api/cron/hiring-watchdog",
    schedule: "*/10 * * * *",
    description: "Сторож найма: таймаут-алерты по зависшим этапам воронки",
  },
  {
    name: "hot-candidate-alerts",
    endpoint: "/api/cron/hot-candidate-alerts",
    schedule: "*/30 * * * *",
    description: "Уведомления HR о «горячих» кандидатах, которые остывают без ответа",
  },
  {
    name: "interview-reminders",
    endpoint: "/api/cron/interview-reminders",
    schedule: "*/5 * * * *",
    description: "Напоминания участникам интервью за 24ч / 1ч / 15 мин",
  },
  {
    name: "knowledge-freshness",
    endpoint: "/api/cron/knowledge-freshness",
    schedule: null,
    description: "Проверка актуальности материалов базы знаний, уведомление директора",
  },
  {
    name: "knowledge-gaps",
    endpoint: "/api/cron/knowledge-gaps",
    schedule: null,
    description: "Анализ пробелов в базе знаний по неотвеченным вопросам за неделю",
  },
  {
    name: "knowledge-progress",
    endpoint: "/api/cron/knowledge-progress",
    schedule: null,
    description: "Недельная сводка прогресса обучения по назначениям",
  },
  {
    name: "knowledge-reminders",
    endpoint: "/api/cron/knowledge-reminders",
    schedule: null,
    description: "Ежедневные напоминания сотрудникам об учебных назначениях с дедлайном < 3 дней",
  },
  {
    name: "knowledge-review",
    endpoint: "/api/cron/knowledge-review",
    schedule: null,
    description: "Пометка материалов базы знаний, требующих проверки (истекающий срок)",
  },
  {
    name: "learn-given-names",
    endpoint: "/api/cron/learn-given-names",
    schedule: null,
    description: "Обновление словаря имён кандидатов для корректного обращения",
  },
  {
    name: "pending-rejections",
    endpoint: "/api/cron/pending-rejections",
    schedule: "*/5 * * * *",
    description: "Исполнение отложенных отказов кандидатам",
  },
  {
    name: "prequalification",
    endpoint: "/api/cron/prequalification",
    schedule: null,
    description: "Предквалификация: напоминания и финализация по истечении срока",
  },
  {
    name: "price-monitor-tick",
    endpoint: "/api/cron/price-monitor-tick",
    schedule: "*/15 * * * *",
    description: "Тик мониторинга цен: проверка объектов и отправка уведомлений",
  },
  {
    name: "pulse-alerts",
    endpoint: "/api/cron/pulse-alerts",
    schedule: null,
    description: "Алерты по низким оценкам в pulse-опросах за 7 дней",
  },
  {
    name: "recalculate-flight-risk",
    endpoint: "/api/cron/recalculate-flight-risk",
    schedule: null,
    description: "Пересчёт баллов риска увольнения для всех сотрудников",
  },
  {
    name: "recalculate-integrator-levels",
    endpoint: "/api/cron/recalculate-integrator-levels",
    schedule: null,
    description: "Пересчёт уровней интеграторов по количеству клиентов",
  },
  {
    name: "sales-follow-up",
    endpoint: "/api/cron/sales-follow-up",
    schedule: "*/15 * * * *",
    description: "Автоматическое дожимание лидов в модуле продаж (SalesRadar)",
  },
  {
    name: "salesradar-attribute",
    endpoint: "/api/cron/salesradar-attribute",
    schedule: "*/2 * * * *",
    description: "SalesRadar: привязка входящих сообщений к сделкам",
  },
  {
    name: "salesradar-pull",
    endpoint: "/api/cron/salesradar-pull",
    schedule: "*/5 * * * *",
    description: "SalesRadar: импорт новых сообщений из подключённых каналов",
  },
  {
    name: "talent-pool-cleanup",
    endpoint: "/api/cron/talent-pool-cleanup",
    schedule: "30 0 * * *",
    description: "Удаление просроченных записей резерва талантов",
  },
  {
    name: "telegram-posting-tick",
    endpoint: "/api/cron/telegram-posting-tick",
    schedule: "*/5 * * * *",
    description: "Тик очереди публикаций в Telegram-каналы",
  },
  {
    name: "test-scoring-retry",
    endpoint: "/api/cron/test-scoring-retry",
    schedule: "*/10 * * * *",
    description: "Повтор AI-скоринга тестов в статусах pending/failed",
  },
  {
    name: "tip-reaper",
    endpoint: "/api/cron/tip-reaper",
    schedule: "*/15 * * * *",
    description: "Очистка зависших прогонов модуля «Типология»",
  },
  {
    name: "trash-cleanup",
    endpoint: "/api/cron/trash-cleanup",
    schedule: "0 0 * * *",
    description: "Физическое удаление вакансий и компаний из корзины по истечении срока хранения",
  },
  {
    name: "yandex-direct-agent",
    endpoint: "/api/cron/yandex-direct-agent",
    schedule: "0 3,9,15,21 * * *",
    description: "AI-агент Яндекс.Директа: синхронизация, оптимизация ставок, автопилот",
  },
]
