export interface CronEntry {
  name: string
  endpoint: string
  schedule: string | null
  description: string
}

export const CRON_REGISTRY: CronEntry[] = [
  {
    name: "adaptation",
    endpoint: "/api/cron/adaptation",
    schedule: null,
    description: "Отправляет шаги адаптации сотрудникам и продвигает текущий день плана",
  },
  {
    name: "ai-chatbot-watcher",
    endpoint: "/api/cron/ai-chatbot-watcher",
    schedule: "0 * * * *",
    description: "Периодический аудит AI-чат-бота: анализ последних сообщений на нарушения",
  },
  {
    name: "ai-rop-billing",
    endpoint: "/api/cron/ai-rop-billing",
    schedule: "0 1 * * *",
    description: "Ежедневное выставление счетов за AI-РОП (Call-Pilot)",
  },
  {
    name: "ai-rop-crm-outcomes",
    endpoint: "/api/cron/ai-rop-crm-outcomes",
    schedule: "0 */6 * * *",
    description: "Синхронизация исходов звонков AI-РОП с CRM",
  },
  {
    name: "ai-rop-import",
    endpoint: "/api/cron/ai-rop-import",
    schedule: "*/5 * * * *",
    description: "Импорт новых звонков для AI-РОП (Call-Pilot)",
  },
  {
    name: "ai-rop-process",
    endpoint: "/api/cron/ai-rop-process",
    schedule: "* * * * *",
    description: "Обработка очереди звонков AI-РОП: STT, анализ, скоринг",
  },
  {
    name: "ai-rop-reports",
    endpoint: "/api/cron/ai-rop-reports",
    schedule: "* * * * *",
    description: "Генерация отчётов AI-РОП по звонкам",
  },
  {
    name: "ai-rop-retry",
    endpoint: "/api/cron/ai-rop-retry",
    schedule: "*/30 * * * *",
    description: "Повторная обработка зависших звонков AI-РОП",
  },
  {
    name: "auto-invoices",
    endpoint: "/api/cron/auto-invoices",
    schedule: "0 6 * * *",
    description: "Автоматическое выставление счетов компаниям по подписке",
  },
  {
    name: "avito-incoming-messages",
    endpoint: "/api/cron/avito-incoming-messages",
    schedule: "*/15 * * * *",
    description: "Резервный обработчик входящих сообщений Авито (страховка при таймауте webhook)",
  },
  {
    name: "b9-status-sanity",
    endpoint: "/api/cron/b9-status-sanity",
    schedule: "0 * * * *",
    description: "Проверка и починка дублирующихся статусов кандидатов (баг B9)",
  },
  {
    name: "check-subscriptions",
    endpoint: "/api/cron/check-subscriptions",
    schedule: null,
    description: "Переводит компании с истёкшим триалом в статус expired",
  },
  {
    name: "data-retention",
    endpoint: "/api/cron/data-retention",
    schedule: "0 1 * * *",
    description: "Удаление устаревших данных по политике хранения (data retention)",
  },
  {
    name: "dev-activity",
    endpoint: "/api/cron/dev-activity",
    schedule: "*/15 * * * *",
    description: "Обновление метрик активности разработки (dev activity)",
  },
  {
    name: "flight-price-watch",
    endpoint: "/api/cron/flight-price-watch",
    schedule: "0 4,10,16,22 * * *",
    description: "Мониторинг цен на авиабилеты и уведомления о снижении",
  },
  {
    name: "flight-risk-alerts",
    endpoint: "/api/cron/flight-risk-alerts",
    schedule: null,
    description: "Создаёт уведомления для сотрудников с высоким/критическим риском увольнения",
  },
  {
    name: "follow-up",
    endpoint: "/api/cron/follow-up",
    schedule: "*/15 * * * *",
    description: "Дожим кандидатов: отправка сообщений по расписанию воронки",
  },
  {
    name: "funnel-v2-tick",
    endpoint: "/api/cron/funnel-v2-tick",
    schedule: "*/5 * * * *",
    description: "Периодический тик рантайма воронки v2: проверка стадий и автопродвижение",
  },
  {
    name: "ghost-candidate-cleanup",
    endpoint: "/api/cron/ghost-candidate-cleanup",
    schedule: "30 0 * * *",
    description: "Удаление призраков-кандидатов (анонимные демо-визиты без действий)",
  },
  {
    name: "health-check",
    endpoint: "/api/cron/health-check",
    schedule: null,
    description: "Проверяет актуальность последних прогонов критичных кронов",
  },
  {
    name: "hh-cleanup-stuck",
    endpoint: "/api/cron/hh-cleanup-stuck",
    schedule: null,
    description: "Переводит застрявшие hh-отклики (rejected/hired кандидатов) в orphaned",
  },
  {
    name: "hh-import",
    endpoint: "/api/cron/hh-import",
    schedule: "*/5 * * * *",
    description: "Импорт откликов с hh.ru и разбор очереди AI-обработки",
  },
  {
    name: "hh-import-burst",
    endpoint: "/api/cron/hh-import-burst",
    schedule: null,
    description: "Пакетный многоитерационный разбор очереди hh (UI-кнопка «Разобрать всё»)",
  },
  {
    name: "hh-incoming-messages",
    endpoint: "/api/cron/hh-incoming-messages",
    schedule: "*/5 * * * *",
    description: "Тянет входящие сообщения кандидатов из hh-чата и применяет действия",
  },
  {
    name: "hh-negotiation-sync",
    endpoint: "/api/cron/hh-negotiation-sync",
    schedule: "*/15 * * * *",
    description: "Синхронизация статусов переговоров (negotiations) с hh.ru",
  },
  {
    name: "hh-token-refresh",
    endpoint: "/api/cron/hh-token-refresh",
    schedule: "0 5 * * *",
    description: "Обновляет истёкшие hh-токены у дормантных компаний",
  },
  {
    name: "hh-vacancy-sync",
    endpoint: "/api/cron/hh-vacancy-sync",
    schedule: "30 2 * * *",
    description: "Синхронизация архивного статуса вакансий с hh.ru",
  },
  {
    name: "hiring-watchdog",
    endpoint: "/api/cron/hiring-watchdog",
    schedule: "*/10 * * * *",
    description: "Сторожевой таймер найма: уведомления о стагнирующих кандидатах",
  },
  {
    name: "hot-candidate-alerts",
    endpoint: "/api/cron/hot-candidate-alerts",
    schedule: "*/30 * * * *",
    description: "Уведомления о горячих кандидатах (быстрые ответы, высокий скоринг)",
  },
  {
    name: "interview-reminders",
    endpoint: "/api/cron/interview-reminders",
    schedule: "*/5 * * * *",
    description: "Напоминания о запланированных собеседованиях кандидатам и HR",
  },
  {
    name: "knowledge-freshness",
    endpoint: "/api/cron/knowledge-freshness",
    schedule: null,
    description: "Проверяет актуальность материалов базы знаний, уведомляет об устаревших",
  },
  {
    name: "knowledge-gaps",
    endpoint: "/api/cron/knowledge-gaps",
    schedule: null,
    description: "Еженедельно: анализирует пробелы в базе знаний, рекомендует новые материалы",
  },
  {
    name: "knowledge-progress",
    endpoint: "/api/cron/knowledge-progress",
    schedule: null,
    description: "Еженедельно: сводка по прогрессу обучения сотрудников",
  },
  {
    name: "knowledge-reminders",
    endpoint: "/api/cron/knowledge-reminders",
    schedule: null,
    description: "Ежедневно: напоминания сотрудникам о курсах с дедлайном < 3 дней",
  },
  {
    name: "knowledge-review",
    endpoint: "/api/cron/knowledge-review",
    schedule: null,
    description: "Флагует материалы базы знаний, требующие проверки по циклу или дате",
  },
  {
    name: "learn-given-names",
    endpoint: "/api/cron/learn-given-names",
    schedule: null,
    description: "Дообучение модели определения имён кандидатов по накопленным данным",
  },
  {
    name: "pending-rejections",
    endpoint: "/api/cron/pending-rejections",
    schedule: "*/5 * * * *",
    description: "Отправляет отложенные отказы кандидатам через hh.ru",
  },
  {
    name: "prequalification",
    endpoint: "/api/cron/prequalification",
    schedule: "*/15 * * * *",
    description: "AI-предквалификация кандидатов: напоминания, таймауты, финализация",
  },
  {
    name: "price-monitor-tick",
    endpoint: "/api/cron/price-monitor-tick",
    schedule: null,
    description: "Тик мониторинга цен (модуль прайс-мониторинга)",
  },
  {
    name: "pulse-alerts",
    endpoint: "/api/cron/pulse-alerts",
    schedule: null,
    description: "Создаёт уведомления по низким оценкам в пульс-опросах сотрудников",
  },
  {
    name: "recalculate-flight-risk",
    endpoint: "/api/cron/recalculate-flight-risk",
    schedule: null,
    description: "Пересчитывает риск-баллы увольнения по всем сотрудникам",
  },
  {
    name: "recalculate-integrator-levels",
    endpoint: "/api/cron/recalculate-integrator-levels",
    schedule: null,
    description: "Пересчитывает уровни интеграторов по количеству клиентов",
  },
  {
    name: "sales-follow-up",
    endpoint: "/api/cron/sales-follow-up",
    schedule: "*/15 * * * *",
    description: "Дожим лидов в модуле продаж (SalesRadar)",
  },
  {
    name: "salesradar-attribute",
    endpoint: "/api/cron/salesradar-attribute",
    schedule: "*/2 * * * *",
    description: "Привязка входящих сообщений SalesRadar к сделкам и контрагентам",
  },
  {
    name: "salesradar-pull",
    endpoint: "/api/cron/salesradar-pull",
    schedule: "*/5 * * * *",
    description: "Тянет новые сообщения из каналов SalesRadar (IMAP/Telegram/WhatsApp)",
  },
  {
    name: "talent-pool-cleanup",
    endpoint: "/api/cron/talent-pool-cleanup",
    schedule: "30 0 * * *",
    description: "Очистка устаревших записей в пуле талантов",
  },
  {
    name: "telegram-posting-tick",
    endpoint: "/api/cron/telegram-posting-tick",
    schedule: "*/5 * * * *",
    description: "Отправка отложенных Telegram-постов (модуль маркетинга)",
  },
  {
    name: "test-scoring-retry",
    endpoint: "/api/cron/test-scoring-retry",
    schedule: "*/10 * * * *",
    description: "Повторный AI-скоринг тестовых заданий при ошибках предыдущей попытки",
  },
  {
    name: "tip-reaper",
    endpoint: "/api/cron/tip-reaper",
    schedule: "*/15 * * * *",
    description: "Завершает устаревшие чаевые-транзакции (TIP-модуль)",
  },
  {
    name: "trash-cleanup",
    endpoint: "/api/cron/trash-cleanup",
    schedule: "0 0 * * *",
    description: "Навсегда удаляет вакансии/компании из корзины по истечении срока хранения",
  },
  {
    name: "yandex-direct-agent",
    endpoint: "/api/cron/yandex-direct-agent",
    schedule: "0 3,9,15,21 * * *",
    description: "AI-агент Яндекс.Директа: синхронизация, оптимизация ставок и бюджетов",
  },
]
